-- MySQL Script generated by MySQL Workbench
-- Tue Jun  3 18:33:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema puiggram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puiggram` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `puiggram` ;

-- -----------------------------------------------------
-- Table `puiggram`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puiggram`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `puiggram`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT ,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `imagen_perfil` VARCHAR(255) NULL DEFAULT NULL,
  `cuenta_publica` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descripcion` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) ,
  UNIQUE INDEX `correo` (`correo` ASC) )
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `puiggram`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puiggram`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `puiggram`.`publicaciones` (
  `id_publicacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `contenido` VARCHAR(300) NULL DEFAULT NULL,
  `tipo` ENUM('imagen', 'video') NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_publicacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_publicacion`),
  INDEX `id_usuario` (`id_usuario` ASC) ,
  CONSTRAINT `publicaciones_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `puiggram`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `puiggram`.`megusta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puiggram`.`megusta` ;

CREATE TABLE IF NOT EXISTS `puiggram`.`megusta` (
  `id_megusta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_publicacion` INT(11) NOT NULL,
  `fecha_megusta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_megusta`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC, `id_publicacion` ASC) ,
  INDEX `id_publicacion` (`id_publicacion` ASC) ,
  CONSTRAINT `megusta_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `puiggram`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `megusta_ibfk_2`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `puiggram`.`publicaciones` (`id_publicacion`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `puiggram`.`mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puiggram`.`mensajes` ;

CREATE TABLE IF NOT EXISTS `puiggram`.`mensajes` (
  `id_mensaje` INT(11) NOT NULL AUTO_INCREMENT,
  `id_emisor` INT(11) NOT NULL,
  `id_receptor` INT(11) NOT NULL,
  `mensaje` MEDIUMTEXT NOT NULL,
  `fecha_envio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_mensaje`),
  INDEX `id_emisor` (`id_emisor` ASC) ,
  INDEX `id_receptor` (`id_receptor` ASC) ,
  CONSTRAINT `mensajes_ibfk_1`
    FOREIGN KEY (`id_emisor`)
    REFERENCES `puiggram`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `mensajes_ibfk_2`
    FOREIGN KEY (`id_receptor`)
    REFERENCES `puiggram`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `puiggram`.`seguidores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puiggram`.`seguidores` ;

CREATE TABLE IF NOT EXISTS `puiggram`.`seguidores` (
  `id_seguidor` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_seguido` INT(11) NOT NULL,
  `fecha_seguimiento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_seguidor`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC, `id_seguido` ASC) ,
  INDEX `id_seguido` (`id_seguido` ASC) ,
  CONSTRAINT `seguidores_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `puiggram`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `seguidores_ibfk_2`
    FOREIGN KEY (`id_seguido`)
    REFERENCES `puiggram`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `puiggram`;

DELIMITER $$

USE `puiggram`$$
DROP TRIGGER IF EXISTS `puiggram`.`set_default_imagen_perfil` $$
USE `puiggram`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `puiggram`.`set_default_imagen_perfil`
BEFORE INSERT ON `puiggram`.`usuarios`
FOR EACH ROW
BEGIN
    SET NEW.imagen_perfil = '../../public/assets/default/perfil_por_defecto.png';
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





INSERT INTO `puiggram`.`usuarios` (`nombre_usuario`, `nombre_completo`, `correo`, `contrasena`, `cuenta_publica`, `descripcion`) VALUES ('Pablo_20', 'Pablo Lopez', 'pablo@gmail.com', '1234', '1', 'Descansando.');
INSERT INTO `puiggram`.`usuarios` (`nombre_usuario`, `nombre_completo`, `correo`, `contrasena`, `cuenta_publica`, `descripcion`) VALUES ('JesusJavier', 'Jesus Díaz', 'diaz@gmail.com', '1234', '1', 'No puedo hablar, solo PuigGram.');
INSERT INTO `puiggram`.`usuarios` (`nombre_usuario`, `nombre_completo`, `correo`, `contrasena`, `cuenta_publica`, `descripcion`) VALUES ('Marta_DZ', 'Marta Dazario', 'marta@gmail.com', '1234', '1', 'En el gimnasio.');
INSERT INTO `puiggram`.`usuarios` (`nombre_usuario`, `nombre_completo`, `correo`, `contrasena`, `cuenta_publica`, `descripcion`) VALUES ('_miguel05', 'Miguel Galetano', 'miguel@gmail.com', '1234', '1', 'En el trabajo.');
INSERT INTO `puiggram`.`usuarios` (`nombre_usuario`, `nombre_completo`, `correo`, `contrasena`, `cuenta_publica`, `descripcion`) VALUES ('Davids', 'Davides Creators', 'david@gmail.com', '1234', '1', 'Los Creadores.');
